<?php 
class message_template{

	public function create_template($headline,$purpose,$name,$content,$logopath,$replyteam,$faqcont){
		$fulltemplate = '<html><head><meta content="text/html; charset=utf-8" /><title>Newsletter</title><link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,800,700|Roboto:100,300,400,500,700,900" rel="stylesheet"></head><body style="padding: 0; margin: 0;font-family: \'Roboto\', sans-serif; font-weight: 300;"><table width="700" border="0" cellspacing="0" cellpadding="0" align="center" style="background: url(\'http://vikash.webgrity.net/carwrap/administrator/images/email-bg.jpg\') repeat-y center top #fff;font-family: \'Roboto\', sans-serif;"><tr><td><table width="670" border="0" cellspacing="0" cellpadding="0" align="center" ><tr><td><table width="550" border="0" cellspacing="0" cellpadding="0" align="center" style=" font-weight: 300; font-size: 17px; line-height: 30px; color: #131212;"><tr><td height="38"></td></tr><tr><td align="center"><a href="#"><img src="' . $logopath . '" height="79" width="257"></a></td></tr><tr><td height="24"></td></tr><tr><td align="center" height="1" bgcolor="cfcfcf"></td></tr><tr><td height="12"></td></tr><tr><td align="center" style="font-size: 19px; color: #080808; letter-spacing: 1px;"><span style="font-weight: 300;">' . $headline . '</span><b>' . $purpose . '!</b></td></tr><tr><td height="12"></td></tr><tr><td align="center" height="1" bgcolor="cfcfcf"></td></tr><tr><td height="35"></td></tr><tr><td style="letter-spacing: 1px; font-size: 19px;"><b>Dear ' . $name . ',</b></td></tr><tr><td height="15"></td></tr><tr><td style="font-weight: 100;"><p>' . $content . '</p><p>' . $faqcont . '</p><p>Best Wishes,<br><b>' . $replyteam . '</b><br>Carwrap Inc. ,Lorem Ipsum , Lorem Ipsum 256, 84 Lorem Ipsum<br><a href="#" style="color: #131212;"><b><i>Carwrap.com</i></b></a></p> </td></tr> <tr><td height="50"></td></tr></table></td></tr></table></td></tr><tr><td><table width="670" border="0" cellspacing="0" cellpadding="0" align="center" bgcolor="#e5e5e5"><tr><td height="13"></td></tr><tr><td align="center" style="font-size: 15px; color: #131212; text-transform: uppercase; letter-spacing: 1.5px;"><p>Carwrap, Contrary to popular belief 1234, 5889, Lorem Ipsum</p></td></tr><tr><td height="13"></td></tr></table></td></tr><tr><td height="42"></td></tr></table></body></html>';

		return $fulltemplate;
	}
}

?>